[package]
name = "c6"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "2"
openssl-sys = "0.9"
openssl = "0.10"
libreria_condivisa={path="../../libreria_condivisa"}
