[package]
name = "c4"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
openssl-sys = "0.9"
openssl = "0.10"
hex="0.4.3"
libreria_condivisa={path="../../libreria_condivisa"}
